version: '3'
services:
    cryptocop-api:
        build: ./cryptocop.Software.Api
        container_name: ./cryptocop.Software.Api
        ports:
            - "5001"
        networks:
            - "cryptocop-network"
    cryptocop-payments:
        build: ./cryptocop/cryptocop-payments
        container_name: cryptocop-payments
        networks:
            - "cryptocop-network"
    cryptocop-emails:
        build: ./cryptocop/cryptocop-emails
        container_name: cryptocop-emails
        networks:
            - "cryptocop-network"
    cryptocop-db:
        image: PostgreSQL
        container_name: cryptocop-db
        networks:
            - "cryptocop-network"
networks:
    cryptocop-network:
        driver: bridge